---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: geerlingguy
    - COLLECTION_NAME: php_roles
  matrix:
    - DISTRO: centos7
    - DISTRO: ubuntu1804

install:
  # Install Ansible from source (only devel has ansible-test currently).
  - git clone https://github.com/ansible/ansible.git
  - cd ansible
  - source ./hacking/env-setup

before_script:
  # Move the collection into the required path to make ansible-test work.
  - cd ../
  - ls
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - ls ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Run tests.
  - ansible-test integration --docker geerlingguy/docker-$DISTRO-ansible
