---
language: python
services: docker

env:
  global:
    - COLLECTION_NAMESPACE: geerlingguy
    - COLLECTION_NAME: php_roles
  matrix:
    - DISTRO: centos7
      TAG: python2
      PYTHON_INTERPRETER: /usr/bin/python3
      PYTHON_VERSION: '3.6'
    - DISTRO: ubuntu1804
      TAG: latest
      PYTHON_INTERPRETER: /usr/bin/python3
      PYTHON_VERSION: '3.6'

install:
  # Install Ansible.
  - pip install ansible

before_script:
  # Move the collection into the required path to make ansible-test work.
  - cd ../
  - mkdir -p ansible_collections/$COLLECTION_NAMESPACE
  - mv ansible-collection-$COLLECTION_NAME ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME
  - cd ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

script:
  # Run tests.
  - ansible-test integration --docker geerlingguy/docker-$DISTRO-ansible:$TAG --python $PYTHON_VERSION --python-interpreter $PYTHON_INTERPRETER
